import Header from "./header/header";
import Footer from "./footer/footer";
import "./styles.css"

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body>
        
        <Header />
 
          {children}

        <Footer />

      </body>
    </html>
  );
}
